// Client-side data layer: mirrors src/lib/data.ts but reads JSON via
// static imports so the bundle works in Tauri's WKWebView and on Vercel
// without `server-only`. Server pages keep using data.ts; pages that
// run in BUILD_TARGET=tauri's static export read this file instead.
//
// Schema validation runs once per call. Snapshots + meta come from
// scripts/build_static_meta.py output (data/meta-static.json), which the
// predeploy:tauri pipeline regenerates before every Tauri build.

import { z } from "zod";

import {
  DealerSchema,
  IncentiveSchema,
  InventoryUnitSchema,
  MarketIntelSchema,
  SnapshotSchema,
  SpecSchema,
  TaxesAndFeesSchema,
  UsedListingSchema,
  type Dealer,
  type Incentive,
  type InventoryUnit,
  type MarketIntel,
  type ScoredUnit,
  type Snapshot,
  type Spec,
  type TaxesAndFees,
  type UsedListing,
  type UsedMarketStat,
} from "./types";
import { MODELS } from "./constants";
import { applicableIncentives, computeDealScore, computeFinanceOtd, computeLeaseOtd, computeOtd } from "./scoring";

// Static JSON bundle imports — tree-shaken per route at build time.
import dealersJson from "@/data/dealers.json";
import unitsJson from "@/data/units.json";
import incentivesJson from "@/data/incentives.json";
import specsJson from "@/data/specs.json";
import taxesJson from "@/data/taxes-and-fees.json";
import marketIntelJson from "@/data/market-intel.json";
import usedListingsJson from "@/data/used-listings.json";
import enrichmentJson from "@/data/units-enrichment.json";

// Optional meta-static.json (generated by scripts/build_static_meta.py).
// Module is committed but the JSON ships dummy values until first
// predeploy:tauri run; production pipeline regenerates it.
import metaStaticJson from "@/data/meta-static.json";

// ----- single-source loaders (mirror data.ts API surface) -----

export async function loadDealers(): Promise<Dealer[]> {
  const base = z.array(DealerSchema).parse(dealersJson);
  // Backfill dealer phone + address from per-listing enrichment when
  // dealers.json still has placeholder values. Same logic as data.ts.
  const enrichment = enrichmentJson as Record<string, { phone?: string; streetAddress?: string }>;
  const unitsRaw = unitsJson as Array<{ id: string; dealerId: string }>;
  const dealerEnrich = new Map<string, { phone?: string; streetAddress?: string }>();
  for (const u of unitsRaw) {
    const e = enrichment[u.id];
    if (!e) continue;
    if (!dealerEnrich.has(u.dealerId)) dealerEnrich.set(u.dealerId, e);
  }
  return base.map((d) => {
    const e = dealerEnrich.get(d.id);
    if (!e) return d;
    const phone = !d.phone && e.phone ? e.phone : d.phone;
    const address =
      (!d.address || d.address === "Address not yet captured") && e.streetAddress
        ? e.streetAddress
        : d.address;
    return { ...d, phone, address };
  });
}

export async function loadUnits(): Promise<InventoryUnit[]> {
  const base = z.array(InventoryUnitSchema).parse(unitsJson);
  const enrichment = enrichmentJson as Record<string, Partial<InventoryUnit>>;
  return base.map((u) => {
    const e = enrichment[u.id];
    if (!e) return u;
    return {
      ...u,
      daysOnLot: e.daysOnLot ?? u.daysOnLot,
      vin: e.vin ?? u.vin,
      msrp: e.msrp ?? u.msrp,
      exteriorColor: e.exteriorColor ?? u.exteriorColor,
      interiorColor: e.interiorColor ?? u.interiorColor,
    };
  });
}

export async function loadIncentives(): Promise<Incentive[]> {
  return z.array(IncentiveSchema).parse(incentivesJson);
}

export async function loadSpecs(): Promise<Spec[]> {
  return z.array(SpecSchema).parse(specsJson);
}

export async function loadTaxesAndFees(): Promise<TaxesAndFees | null> {
  return TaxesAndFeesSchema.parse(taxesJson);
}

export async function loadMarketIntel(): Promise<MarketIntel | null> {
  return MarketIntelSchema.parse(marketIntelJson);
}

export async function loadUsedListings(): Promise<UsedListing[]> {
  return z.array(UsedListingSchema).parse(usedListingsJson);
}

// ----- shared utility re-exports (identical bodies to data.ts) -----

const HALO_TRIM_REGEX = /\b(GT|N|Performance|Calligraphy)\b/i;

export function computeUsedMarketStats(
  used: UsedListing[],
  specs: Spec[],
  includeHaloTrims = false,
): UsedMarketStat[] {
  const median = (arr: number[]): number => {
    if (!arr.length) return 0;
    const sorted = [...arr].sort((a, b) => a - b);
    const mid = Math.floor(sorted.length / 2);
    return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
  };
  const newMsrpByModel = new Map<string, number>();
  for (const s of specs) {
    if (!s.msrpCad) continue;
    if (!includeHaloTrims && HALO_TRIM_REGEX.test(s.trim)) continue;
    const cur = newMsrpByModel.get(s.model);
    if (cur == null || s.msrpCad < cur) newMsrpByModel.set(s.model, s.msrpCad);
  }
  return MODELS.map((model) => {
    const rows = used.filter((u) => u.model === model);
    const prices = rows.map((u) => u.priceCad);
    const kms = rows.map((u) => u.kmDriven);
    const medPrice = median(prices);
    const newFloor = newMsrpByModel.get(model) ?? null;
    return {
      model,
      count: rows.length,
      medianPriceCad: medPrice,
      minPriceCad: prices.length ? Math.min(...prices) : 0,
      maxPriceCad: prices.length ? Math.max(...prices) : 0,
      medianKm: median(kms),
      newMsrpFloorCad: newFloor,
      retentionPercent: newFloor && medPrice ? Math.round((medPrice / newFloor) * 100) : null,
    };
  }).filter((s) => s.count > 0);
}

export function specKey(model: string, year: number, trim: string, drivetrain: string): string {
  return `${model}|${year}|${trim}|${drivetrain}`;
}

export function specMap(specs: Spec[]): Map<string, Spec> {
  return new Map(specs.map((s) => [specKey(s.model, s.year, s.trim, s.drivetrain), s]));
}

// ----- meta + snapshots (from generated meta-static.json) -----

export type DataMeta = {
  unitsUpdatedAt: string;
  incentivesUpdatedAt: string;
  dealersUpdatedAt: string;
  snapshotCount: number;
  lastSnapshotAt: string | null;
};

type MetaStaticShape = {
  unitsUpdatedAt: string;
  incentivesUpdatedAt: string;
  dealersUpdatedAt: string;
  snapshotCount: number;
  lastSnapshotAt: string | null;
  snapshotFiles: string[];
  snapshots: unknown[];
};

const META = metaStaticJson as MetaStaticShape;

export async function loadMeta(): Promise<DataMeta> {
  return {
    unitsUpdatedAt: META.unitsUpdatedAt,
    incentivesUpdatedAt: META.incentivesUpdatedAt,
    dealersUpdatedAt: META.dealersUpdatedAt,
    snapshotCount: META.snapshotCount,
    lastSnapshotAt: META.lastSnapshotAt,
  };
}

export async function listSnapshotFiles(): Promise<string[]> {
  return [...META.snapshotFiles];
}

export async function loadSnapshots(limit?: number): Promise<Snapshot[]> {
  const all = z.array(SnapshotSchema).parse(META.snapshots);
  return limit ? all.slice(-limit) : all;
}

// ----- consolidated dataset (mirrors data.ts:loadScoredUnits) -----

export async function loadScoredUnits(
  buyerContextOrProvince?: import("./types").BuyerContext | import("./constants").Province,
): Promise<{
  units: ScoredUnit[];
  dealers: Dealer[];
  dealerById: Map<string, Dealer>;
  incentives: Incentive[];
  buyerContext: import("./types").BuyerContext | null;
  buyerProvince: import("./constants").Province | null;
}> {
  const buyerContext: import("./types").BuyerContext | undefined =
    typeof buyerContextOrProvince === "string"
      ? { province: buyerContextOrProvince, loyalty: false, conquest: false }
      : buyerContextOrProvince;

  const [units, dealers, incentives] = await Promise.all([
    loadUnits(),
    loadDealers(),
    loadIncentives(),
  ]);
  const dealerById = new Map(dealers.map((d) => [d.id, d]));
  const unitsByDealer = new Map<string, InventoryUnit[]>();
  for (const u of units) {
    const arr = unitsByDealer.get(u.dealerId) ?? [];
    arr.push(u);
    unitsByDealer.set(u.dealerId, arr);
  }

  const scored = units.map((unit) => {
    const dealer = dealerById.get(unit.dealerId);
    if (!dealer) {
      throw new Error(`Unit ${unit.id} references unknown dealer ${unit.dealerId}`);
    }
    const applicable = applicableIncentives(unit, dealer, incentives, buyerContext);
    const otdBreakdown = computeOtd(unit, dealer, applicable, buyerContext?.province);
    const finance = computeFinanceOtd(unit, dealer, applicable, buyerContext);
    const lease = computeLeaseOtd(unit, dealer, applicable, buyerContext);
    const { score, breakdown } = computeDealScore({
      unit,
      dealer,
      dealerUnits: unitsByDealer.get(dealer.id) ?? [],
      applicable,
    });
    return {
      ...unit,
      otdCad: otdBreakdown.total,
      otdBreakdown,
      otdPaths: {
        cash: otdBreakdown,
        ...(finance ? { finance } : {}),
        ...(lease ? { lease } : {}),
      },
      dealScore: score,
      dealScoreBreakdown: breakdown,
      applicableIncentives: applicable,
    } satisfies ScoredUnit;
  });

  return {
    units: scored,
    dealers,
    dealerById,
    incentives,
    buyerContext: buyerContext ?? null,
    buyerProvince: buyerContext?.province ?? null,
  };
}
