#!/usr/bin/env python3
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CODEX_DIR = ROOT / ".codex"
OUT = CODEX_DIR / "compact-context.md"
SAFE_OUT = CODEX_DIR / "safe-area.md"
ACTIVE_FILES = CODEX_DIR / "active-files.txt"


def read(path: str, limit: int = 5000) -> str:
    file = ROOT / path
    if not file.exists():
        return ""
    text = file.read_text(encoding="utf-8", errors="replace")
    return text[:limit].rstrip()


def run(args: list[str]) -> str:
    try:
        return subprocess.check_output(args, cwd=ROOT, text=True, stderr=subprocess.STDOUT, timeout=8).strip()
    except Exception as exc:
        return f"unavailable: {exc}"


def bullets_from_markdown(text: str, keep: int = 12) -> list[str]:
    lines = []
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("- ") or re.match(r"^\d+\. ", line):
            lines.append(line)
        if len(lines) >= keep:
            break
    return lines


def rg(pattern: str, files: list[str]) -> list[str]:
    existing = [str(ROOT / f) for f in files if (ROOT / f).exists()]
    if not existing:
        return []
    try:
        out = subprocess.check_output(
            ["rg", "-n", pattern, *existing],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
            timeout=8,
        )
        return [line.replace(str(ROOT) + "/", "") for line in out.splitlines()[:30]]
    except Exception:
        return []


task = read("TASK_BOARD.md")
data = read("DATA_CONTRACT.md")
source = read("SOURCE_REGISTRY.md")
reuse = read("REUSE_SCAN.md")
memory = read("MEMORY.md", 8000)

hot_hits = rg(
    r"LeverageDashboardView|ResearchImportValidator|LeverageCalculator|InventoryListing|user_version = 2|buyerPostalCode",
    [
        "Sources/AppModels/DomainModels.swift",
        "Sources/Persistence/AppDatabase.swift",
        "Sources/Calculators/LeverageCalculator.swift",
        "Sources/Support/ResearchTools.swift",
        "Sources/UIComponents/LeverageDashboardView.swift",
        "Sources/Catalog/InventoryStore.swift",
        "Sources/Catalog/CatalogStore.swift",
    ],
)

status = run(["git", "status", "--short"])
tracked_files = run(["git", "ls-files"]).splitlines()
trust_git_status = bool(tracked_files)

active_files = []
untracked_roots = []
if trust_git_status:
    for line in status.splitlines():
        if len(line) <= 3 or not line[:2].strip():
            continue
        path = line[3:].strip()
        if not path:
            continue
        candidate = ROOT / path
        if candidate.is_file():
            active_files.append(path)
        elif candidate.is_dir():
            untracked_roots.append(path.rstrip("/") + "/")
else:
    untracked_roots = [
        line[3:].strip().rstrip("/") + "/"
        for line in status.splitlines()
        if len(line) > 3 and line[:2].strip() and (ROOT / line[3:].strip()).is_dir()
    ]

if ACTIVE_FILES.exists():
    manual_files = [
        line.strip()
        for line in ACTIVE_FILES.read_text(encoding="utf-8", errors="replace").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    active_files.extend(manual_files)
active_files = sorted(set(active_files))

context_budget = 100
active_file_load = min(100, len(active_files) * 6)
hot_anchor_load = min(20, len(hot_hits) // 2)
doc_load = min(30, sum(len(text) for text in [task, data, source, reuse, memory]) // 4000)
context_load = min(100, active_file_load + hot_anchor_load + doc_load)

if context_load >= 70:
    context_zone = "danger"
elif context_load >= 40:
    context_zone = "safe-area"
else:
    context_zone = "normal"

safe_actions = {
    "normal": "Continue normally. Compact before handoff or reasoning downgrade.",
    "safe-area": "Compact now. Finish current file. Avoid broad reads. Prefer one bounded task.",
    "danger": "Stop expansion. Write safe-area snapshot. Verify or pause before more edits.",
}

content = f"""# Compact Context

Generated by `plugins/caveman-skill/scripts/compact_context.py`.

## Mission

Native macOS SwiftUI/SQLite Hyundai/Kia deal leverage dashboard.

Focus:
- 2025-2026 Hyundai/Kia BEV/PHEV/HEV only.
- Rank dealer negotiation leverage, not generic EV browsing.
- Manual refresh + Deep Research CSV/JSON import.
- No invented finance payments.
- Marketplace rows low confidence until dealer/OEM confirmed.

## Current Architecture

- Models: `Sources/AppModels/DomainModels.swift`
- SQLite v2 persistence: `Sources/Persistence/AppDatabase.swift`
- Scoring: `Sources/Calculators/LeverageCalculator.swift`
- Prompt/import validation: `Sources/Support/ResearchTools.swift`
- Dashboard: `Sources/UIComponents/LeverageDashboardView.swift`
- Store state: `Sources/Catalog/InventoryStore.swift`, `Sources/Catalog/CatalogStore.swift`
- Caveman/context skills: `plugins/caveman-skill/skills/`

## Context Load

- Estimated load: {context_load}% of repo-local context budget
- Zone: `{context_zone}`
- Rule: compact at 40%; safe-area handoff at 70%; stop expanding before risky broad reads
- Action: {safe_actions[context_zone]}
- Active files: {len(active_files)}
- Untracked roots ignored for load estimate: {len(untracked_roots)}
- Git status trusted: {"yes" if trust_git_status else "no; repo has no tracked files, use .codex/active-files.txt"}

```text
{chr(10).join(active_files[:40]) if active_files else "No active files detected. Add explicit paths to .codex/active-files.txt during long work."}
```

Ignored untracked roots:

```text
{chr(10).join(untracked_roots[:40]) if untracked_roots else "None."}
```

## Next Tasks

{chr(10).join(bullets_from_markdown(task, 16)) or "- See TASK_BOARD.md"}

## Data Contract

{chr(10).join(bullets_from_markdown(data, 18)) or "- See DATA_CONTRACT.md"}

## Source Policy

{chr(10).join(bullets_from_markdown(source, 18)) or "- See SOURCE_REGISTRY.md"}

## Reuse Scan

{chr(10).join(bullets_from_markdown(reuse, 12)) or "- See REUSE_SCAN.md"}

## Memory Hints

{chr(10).join(bullets_from_markdown(memory, 20)) or "- See MEMORY.md"}

## Hot File Anchors

```text
{chr(10).join(hot_hits) if hot_hits else "No rg anchors found."}
```

## Git Status

```text
{status or "clean/unknown"}
```

## Verification Baseline

Last known good before compaction:
- `CLANG_MODULE_CACHE_PATH=.build/clang-module-cache swift build --product EVAutoTraderApp`
- `CLANG_MODULE_CACHE_PATH=.build/clang-module-cache swift test`
- `./script/build_and_run.sh --verify`

Run SwiftPM commands serially. If one is active, wait.

## Low Reasoning Start

Read:
1. this file
2. `TASK_BOARD.md`
3. `DATA_CONTRACT.md`
4. `SOURCE_REGISTRY.md`
5. `plugins/caveman-skill/skills/caveman-skill/SKILL.md`

Then do exactly one task.
"""

OUT.parent.mkdir(parents=True, exist_ok=True)
if OUT.exists() and OUT.read_text(encoding="utf-8", errors="replace") == content:
    print(f"unchanged {OUT.relative_to(ROOT)}")
else:
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")

safe_content = f"""# Safe Area

Generated by `plugins/caveman-skill/scripts/compact_context.py`.

Use when context load is above 40%, after a medium slice, or before a pause.

## State

- Context load: {context_load}%
- Zone: `{context_zone}`
- Active files: {len(active_files)}
- Untracked roots ignored for load estimate: {len(untracked_roots)}
- Git status trusted: {"yes" if trust_git_status else "no; repo has no tracked files, use .codex/active-files.txt"}
- Next action: {safe_actions[context_zone]}

## Resume Path

1. Read `.codex/compact-context.md`.
2. Read `TASK_BOARD.md`.
3. Pick one task only.
4. Keep active files <= 8.
5. Verify serially.
6. Run `plugins/caveman-skill/scripts/compact_context.py`.

## Active Files

```text
{chr(10).join(active_files[:80]) if active_files else "No active files detected. Add explicit paths to .codex/active-files.txt during long work."}
```

## Ignored Untracked Roots

```text
{chr(10).join(untracked_roots[:80]) if untracked_roots else "None."}
```
"""

if SAFE_OUT.exists() and SAFE_OUT.read_text(encoding="utf-8", errors="replace") == safe_content:
    print(f"unchanged {SAFE_OUT.relative_to(ROOT)}")
else:
    SAFE_OUT.write_text(safe_content, encoding="utf-8")
    print(f"wrote {SAFE_OUT.relative_to(ROOT)}")
