#!/usr/bin/env python3
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / ".codex" / "compact-context.md"


def read(path: str, limit: int = 5000) -> str:
    file = ROOT / path
    if not file.exists():
        return ""
    text = file.read_text(encoding="utf-8", errors="replace")
    return text[:limit].rstrip()


def run(args: list[str]) -> str:
    try:
        return subprocess.check_output(args, cwd=ROOT, text=True, stderr=subprocess.STDOUT, timeout=8).strip()
    except Exception as exc:
        return f"unavailable: {exc}"


def bullets_from_markdown(text: str, keep: int = 12) -> list[str]:
    lines = []
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("- ") or re.match(r"^\d+\. ", line):
            lines.append(line)
        if len(lines) >= keep:
            break
    return lines


def rg(pattern: str, files: list[str]) -> list[str]:
    existing = [str(ROOT / f) for f in files if (ROOT / f).exists()]
    if not existing:
        return []
    try:
        out = subprocess.check_output(
            ["rg", "-n", pattern, *existing],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
            timeout=8,
        )
        return [line.replace(str(ROOT) + "/", "") for line in out.splitlines()[:30]]
    except Exception:
        return []


task = read("TASK_BOARD.md")
data = read("DATA_CONTRACT.md")
source = read("SOURCE_REGISTRY.md")
reuse = read("REUSE_SCAN.md")
memory = read("MEMORY.md", 8000)

hot_hits = rg(
    r"LeverageDashboardView|ResearchImportValidator|LeverageCalculator|InventoryListing|user_version = 2|buyerPostalCode",
    [
        "Sources/AppModels/DomainModels.swift",
        "Sources/Persistence/AppDatabase.swift",
        "Sources/Calculators/LeverageCalculator.swift",
        "Sources/Support/ResearchTools.swift",
        "Sources/UIComponents/LeverageDashboardView.swift",
        "Sources/Catalog/InventoryStore.swift",
        "Sources/Catalog/CatalogStore.swift",
    ],
)

status = run(["git", "status", "--short"])

content = f"""# Compact Context

Generated by `plugins/caveman-skill/scripts/compact_context.py`.

## Mission

Native macOS SwiftUI/SQLite Hyundai/Kia deal leverage dashboard.

Focus:
- 2025-2026 Hyundai/Kia BEV/PHEV/HEV only.
- Rank dealer negotiation leverage, not generic EV browsing.
- Manual refresh + Deep Research CSV/JSON import.
- No invented finance payments.
- Marketplace rows low confidence until dealer/OEM confirmed.

## Current Architecture

- Models: `Sources/AppModels/DomainModels.swift`
- SQLite v2 persistence: `Sources/Persistence/AppDatabase.swift`
- Scoring: `Sources/Calculators/LeverageCalculator.swift`
- Prompt/import validation: `Sources/Support/ResearchTools.swift`
- Dashboard: `Sources/UIComponents/LeverageDashboardView.swift`
- Store state: `Sources/Catalog/InventoryStore.swift`, `Sources/Catalog/CatalogStore.swift`
- Caveman/context skills: `plugins/caveman-skill/skills/`

## Next Tasks

{chr(10).join(bullets_from_markdown(task, 16)) or "- See TASK_BOARD.md"}

## Data Contract

{chr(10).join(bullets_from_markdown(data, 18)) or "- See DATA_CONTRACT.md"}

## Source Policy

{chr(10).join(bullets_from_markdown(source, 18)) or "- See SOURCE_REGISTRY.md"}

## Reuse Scan

{chr(10).join(bullets_from_markdown(reuse, 12)) or "- See REUSE_SCAN.md"}

## Memory Hints

{chr(10).join(bullets_from_markdown(memory, 20)) or "- See MEMORY.md"}

## Hot File Anchors

```text
{chr(10).join(hot_hits) if hot_hits else "No rg anchors found."}
```

## Git Status

```text
{status or "clean/unknown"}
```

## Verification Baseline

Last known good before compaction:
- `CLANG_MODULE_CACHE_PATH=.build/clang-module-cache swift build --product EVAutoTraderApp`
- `CLANG_MODULE_CACHE_PATH=.build/clang-module-cache swift test`
- `./script/build_and_run.sh --verify`

Run SwiftPM commands serially. If one is active, wait.

## Low Reasoning Start

Read:
1. this file
2. `TASK_BOARD.md`
3. `DATA_CONTRACT.md`
4. `SOURCE_REGISTRY.md`
5. `plugins/caveman-skill/skills/caveman-skill/SKILL.md`

Then do exactly one task.
"""

OUT.parent.mkdir(parents=True, exist_ok=True)
if OUT.exists() and OUT.read_text(encoding="utf-8", errors="replace") == content:
    print(f"unchanged {OUT.relative_to(ROOT)}")
else:
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
