#!/usr/bin/env python3
"""changelog.py — regenerate CHANGELOG.md from `git log` (I-09).

Convention: every milestone commit starts with `<id>: <summary>` thanks to
`scripts/milestone.py`. This script parses those, groups by cluster letter
(the leading character of the ID), and writes a human-readable CHANGELOG.md.

Idempotent — runs in <1 s and can be re-run any time. Wired into milestone.py
as step 14 (post-commit) so each milestone keeps the file fresh.

Usage:
    python3 scripts/changelog.py            # write to CHANGELOG.md
    python3 scripts/changelog.py --stdout   # print, don't write
    python3 scripts/changelog.py --since v0.1.0   # only commits since tag
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "CHANGELOG.md"

# Match `<ID>: <summary>` where ID = letters/digits/hyphens.
# Examples: D-04, F-10, RESEARCH-INFRA, H8c, N-PLAN, I-06, A12, B-01.
ID_RE = re.compile(r"^([A-Z][A-Z0-9-]*?[0-9a-z]*?):\s+(.*)$")

# Cluster letter -> (full name, sort order)
CLUSTER_NAMES = {
    "A": ("Cluster A — Foundation rework", 1),
    "B": ("Cluster B — Citation & confidence", 2),
    "C": ("Cluster C — Physics + cost + bug fixes", 3),
    "D": ("Cluster D — Data: vehicles, citations, expansions", 4),
    "E": ("Cluster E — Maps, range rings, trip planning", 5),
    "F": ("Cluster F — Polish, packaging, accessibility", 6),
    "G": ("Cluster G — Reserved", 7),
    "H": ("Cluster H — Token ROI, autonomy, debug logging", 8),
    "I": ("Cluster I — Infrastructure, scripts, integrations", 9),
    "J": ("Cluster J — MapLibre Metal", 10),
    "K": ("Cluster K — Real routing + weather + E2E", 11),
    "L": ("Cluster L — Live inventory", 12),
    "M": ("Cluster M — SwiftUI rewrite (deferred)", 13),
    "N": ("Cluster N — Optimal sequencing + autonomous batch", 14),
    "P": ("Polish items", 15),
    "R": ("Research / standalone", 16),
}


def get_log(since: str | None) -> list[tuple[str, str, str]]:
    """Return list of (hash, date, subject) for every commit, oldest-first."""
    args = ["git", "log", "--reverse", "--no-merges",
            "--format=%h%x09%ad%x09%s", "--date=short"]
    if since:
        args.append(f"{since}..HEAD")
    res = subprocess.run(args, cwd=ROOT, check=True, capture_output=True, text=True)
    out: list[tuple[str, str, str]] = []
    for line in res.stdout.splitlines():
        parts = line.split("\t", 2)
        if len(parts) == 3:
            out.append((parts[0], parts[1], parts[2]))
    return out


def cluster_letter_for(item_id: str) -> str:
    """Map an item ID to its cluster letter."""
    # Special cases first
    upper = item_id.upper()
    if upper.startswith("RESEARCH-INFRA"):
        return "I"
    # First letter, possibly skipping leading non-letter (rare)
    for c in upper:
        if c.isalpha():
            return c
    return "Z"  # unknown bucket


def build_changelog(commits: list[tuple[str, str, str]]) -> str:
    by_cluster: dict[str, list[tuple[str, str, str, str]]] = defaultdict(list)
    other: list[tuple[str, str, str]] = []

    for h, date, subject in commits:
        m = ID_RE.match(subject.strip())
        if not m:
            other.append((h, date, subject))
            continue
        item_id, summary = m.group(1), m.group(2)
        letter = cluster_letter_for(item_id)
        by_cluster[letter].append((h, date, item_id, summary))

    lines: list[str] = []
    lines.append("# Changelog")
    lines.append("")
    lines.append(
        "*Auto-generated by `scripts/changelog.py` from `git log` "
        "(every milestone commit starts with `<id>: <summary>`). "
        "Re-run any time; idempotent.*"
    )
    lines.append("")

    # Sort clusters by their declared order
    def order_key(letter: str) -> int:
        return CLUSTER_NAMES.get(letter, (letter, 99))[1]

    for letter in sorted(by_cluster.keys(), key=order_key):
        name = CLUSTER_NAMES.get(letter, (f"Cluster {letter}", 99))[0]
        lines.append(f"## {name}")
        lines.append("")
        for h, date, item_id, summary in by_cluster[letter]:
            # Truncate over-long subjects so the file stays scannable
            short = summary if len(summary) <= 240 else summary[:237] + "..."
            lines.append(f"- `{h}` **{item_id}** ({date}) — {short}")
        lines.append("")

    if other:
        lines.append("## Uncategorized")
        lines.append("")
        for h, date, subject in other:
            short = subject if len(subject) <= 240 else subject[:237] + "..."
            lines.append(f"- `{h}` ({date}) — {short}")
        lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print to stdout instead of writing CHANGELOG.md")
    ap.add_argument("--since", help="only include commits since this tag/ref")
    args = ap.parse_args(argv[1:])

    commits = get_log(args.since)
    if not commits:
        print("(no commits found)", file=sys.stderr)
        return 0
    text = build_changelog(commits)

    if args.stdout:
        sys.stdout.write(text)
        return 0
    OUT.write_text(text, encoding="utf-8")
    n_clusters = sum(1 for letter in CLUSTER_NAMES if any(line.startswith(f"## {CLUSTER_NAMES[letter][0]}") for line in text.splitlines()))
    print(f"  → CHANGELOG.md: {len(commits)} commits across {n_clusters} clusters")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
