#!/usr/bin/env python3
"""research.py — emit a parallel-dispatch research plan for any topic.

Usage:
    python3 scripts/research.py "<topic>" [--angles N] [--output PATH]
    python3 scripts/research.py "Apple MapKit JS pricing for personal use 2026" --angles 3
    python3 scripts/research.py "EV trip planning libs comparison" --angles 5

The script does NOT make network calls. It generates a structured markdown plan
of N parallel angles + suggested tool dispatches for each. Claude reads the
plan and spawns N agents in one tool batch.

Why a plan-then-execute design? Because Claude can run agents in parallel for
free, but needs to think first about *which* agents to spawn so they don't
overlap. The script provides the cognitive scaffolding so the dispatch is fast
and disjoint.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

DEFAULT_ANGLES = [
    {
        "name": "primary-source",
        "rationale": "Find the canonical / official source for the topic. OEM, vendor, RFC, project website. Highest-confidence facts go here.",
        "tool_preferences": ["WebSearch (official site filter)", "WebFetch on suspected canonical URL"],
    },
    {
        "name": "comparison-survey",
        "rationale": "What are the alternatives? List 3–5 competing options with one-line pros/cons each.",
        "tool_preferences": ["WebSearch \"X vs Y vs Z\"", "Exa semantic search"],
    },
    {
        "name": "recent-changes",
        "rationale": "What changed in the last ~12 months? Pricing shifts, deprecated features, new entrants.",
        "tool_preferences": ["Exa with date filter", "WebSearch with current year in query"],
    },
    {
        "name": "cost-and-licensing",
        "rationale": "Free tier limits, paid tier pricing, license terms (MIT/Apache/proprietary), key requirements.",
        "tool_preferences": ["WebFetch on /pricing pages", "WebSearch \"X license\""],
    },
    {
        "name": "real-world-use",
        "rationale": "Reddit / HN / blog posts from people who actually used it. What broke for them, what surprised them.",
        "tool_preferences": ["WebSearch site:reddit.com OR site:news.ycombinator.com", "Exa semantic"],
    },
    {
        "name": "integration-fit",
        "rationale": "How well does this slot into THIS codebase (Tauri 2 + React + TS + Python scripts)? Existing similar deps?",
        "tool_preferences": ["Local Grep + Glob first", "WebSearch \"X with Tauri\" or \"X with Vite\""],
    },
]


def slugify(s: str) -> str:
    out = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return (out[:60] or "research")


def build_markdown(topic: str, angles: list[dict]) -> str:
    today = date.today().isoformat()
    lines: list[str] = []
    lines.append(f"# Research plan — {topic}")
    lines.append("")
    lines.append(f"*Generated by `scripts/research.py` on {today}.*")
    lines.append("")
    lines.append("**Goal.** Produce a confidence-tagged research note in `docs/research/auto/` "
                 f"covering the topic from {len(angles)} angles in parallel.")
    lines.append("")
    lines.append("**How to execute.** ONE tool message containing all of the following `Agent` calls. "
                 "Each agent runs ≤200 words back. Total wall-clock = slowest agent.")
    lines.append("")
    lines.append("---")
    lines.append("")
    for a in angles:
        lines.append(f"## Agent: `{a['name']}`")
        lines.append("")
        lines.append(f"**Why this angle:** {a['rationale']}")
        lines.append("")
        lines.append("**Suggested tools (in order):**")
        for t in a["tool_preferences"]:
            lines.append(f"- {t}")
        lines.append("")
        lines.append("**Prompt template for this sub-agent:**")
        lines.append("```")
        lines.append(f"You are researching: {topic}")
        lines.append(f"Your specific angle: {a['name']} — {a['rationale']}")
        lines.append("Use the suggested tools above in parallel where possible.")
        lines.append("Return ≤200 words. Bullet list of findings, each ending in [source: <url>].")
        lines.append("Tag each finding with confidence (High = 2+ sources agree, Medium = single source, Low = inferred).")
        lines.append("```")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Aggregation step (after agents return)")
    lines.append("")
    lines.append("Merge findings into a single research note at:")
    lines.append("")
    lines.append(f"```\ndocs/research/auto/{slugify(topic)}-{today}.md\n```")
    lines.append("")
    lines.append("Format: Goal · Findings (deduped, by source) · Confidence per finding · ROI / next steps.")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("topic")
    ap.add_argument("--angles", type=int, default=4, help="number of parallel angles (1–6)")
    ap.add_argument("--output", default="docs/research/auto/")
    args = ap.parse_args(argv[1:])

    n = max(1, min(args.angles, len(DEFAULT_ANGLES)))
    angles = DEFAULT_ANGLES[:n]
    md = build_markdown(args.topic, angles)

    out_dir = ROOT / args.output
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"plan-{slugify(args.topic)}-{date.today().isoformat()}.md"
    path.write_text(md, encoding="utf-8")

    print(f"plan: {path.relative_to(ROOT)}")
    print(f"angles: {n} parallel agents")
    for a in angles:
        print(f"  - {a['name']}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
